### PR TITLE
chore: add CODEOWNERS

### PR DESCRIPTION
**Pull request by derberg**
@fmvilas tbh I'm not sure anyone else can be a codeowner here, unless you know someone from MuleSoft that could join 🤷🏼

### CODE REVIEW

**Comment by derberg** [comment]
we need at least 2 maintainers, otherwise, there will be no one able to approve your PR

**Comment by fmvilas** [comment]
Maybe @jstoiko or someone he knows 🤔

**Comment by jstoiko** [comment]
Thanks for the ping @fmvilas. Let me find out who could own this and circle back here.

**Comment by fmvilas** [comment]
Chatted privately with @jstoiko. You can add him too 👍

**Comment by derberg** [comment]
@fmvilas awesome, thanks!

@jstoiko are you aware of our open governance and that the fact of being a CODEOWNER enables you to become a [TSC member](https://github.com/asyncapi/community/blob/master/CHARTER.md#2-technical-steering-committee)? In case you are interested, please [open up a PR against this file](https://github.com/asyncapi/community/blob/master/TSC_MEMBERS.json)

**Comment by derberg** [comment]
@fmvilas @jstoiko please approve this PR

**Review by fmvilas — APPROVED** [review]

**Comment by derberg** [comment]
@jstoiko pinging in case notification was lost :) please approve this PR if you agree

**Review by jstoiko — APPROVED** [review]

**Pull request merged**
