### PR TITLE
feat!: rewrite to TS and adjust to the v2 ParserJS

### LINKED ISSUE #139: Move RAML Schema parser (TS version) back from parser-js 2.0 to this repo
#### Reason/Context

[Parser-JS 2.0](https://github.com/asyncapi/parser-js/issues/481) (released as rc at this moment) is a completely new parser, with a lot of changes. The bigger ones are:

- Completely rewritten to TS.
- Implements the new [parser-api](https://github.com/asyncapi/parser-api), in particular, the version found in [this PR](https://github.com/asyncapi/parser-api/pull/71/files#diff-ac35ac6e0b0ad3629802a0e04076aa18e94da614f5392e1164dcaacdfe3ee198).
- Uses [Spectral](https://stoplight.io/open-source/spectral) as parser/linter with the [AsyncAPI ruleset](https://meta.stoplight.io/docs/spectral/1e63ffd0220f3-async-api-rules).
- Lots of other improvements, especially around Developer Experience.

Considering that Spectral now validates the documents before parsing, we had to update [the interface](https://github.com/asyncapi/parser-js/tree/next-major#custom-schema-parsers) for Schema parsers to separate validation from parsing. This change also introduced better errors and the way we handle them. (see [this issue](https://github.com/asyncapi/parser-js/issues/480) and related). 

FYI, Spectral addition was discussed starting in https://github.com/asyncapi/parser-js/issues/481#issuecomment-1195965993, ending in https://github.com/asyncapi/parser-js/issues/481#issuecomment-1216436846. Also https://github.com/asyncapi/parser-js/issues/477#issuecomment-1216430740. Also during some [3.0 meetings](https://github.com/asyncapi/community/issues?q=is%3Aissue+is%3Aclosed+%22Spec+3.0+Meeting%22).

To not pollute every single schema parser repository and to simplify development, the schema parsers have been temporarily included in [the same source code](https://github.com/asyncapi/parser-js/tree/next-major/src/schema-parser) as the [Parser-JS 2.0](https://github.com/asyncapi/parser-js/issues/481). Once tested, the idea is to move those back to their own repositories.

#### Description
The work to be done is to move back this schema parser from https://github.com/asyncapi/parser-js/tree/next-major/src/schema-parser to this repository.

This includes:
- Copy-pasting the schema parser code from the Parser-JS 2.0 `next-major` repository to this one.
- Enable Typescript compilation.
- To release a new major version, since the interface has changed.

Please feel free to drop your questions and concerns.

cc @derberg @fmvilas @jstoiko @magicmatatjahu

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- Rewrite to TS.
- Adjust exported module to the new v2 ParserJS Custom Schema Parser interface - new `validate()` function.
- Improve testing and move to the Jest.
- Update Readme.
- Add @magicmatatjahu to the codeowners.

**Related issue(s)**
Resolves #139

### CODE REVIEW

**Comment by smoya** [comment]
@fmvilas @jstoiko as code owners, would you mind doing a review to this? Thanks!

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Comment by fmvilas** [comment]
@magicmatatjahu done 👍

**Review by fmvilas — APPROVED** [review]

**Comment by smoya** [comment]
not stale

**Comment by smoya** [comment]
Please @fmvilas can you merge? I will create a PR later on merging `next-major` in `master`.

**Pull request merged**
